/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_SLASH = 3,
  anon_sym_LT = 4,
  aux_sym_path_reference_token1 = 5,
  anon_sym_GT = 6,
  anon_sym_AMP = 7,
  aux_sym_bare_word_token1 = 8,
  anon_sym_DQUOTE_DQUOTE = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_string_token1 = 11,
  anon_sym_DQUOTE2 = 12,
  anon_sym_AT_DQUOTE = 13,
  aux_sym_verbatim_token1 = 14,
  anon_sym_EQ = 15,
  anon_sym_COLON = 16,
  aux_sym_extension_token1 = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  sym_source_file = 22,
  sym_internal_reference = 23,
  sym_path_reference = 24,
  sym_reference = 25,
  sym_value = 26,
  sym_bare_word = 27,
  sym_string = 28,
  sym_verbatim = 29,
  sym_assignment = 30,
  sym__assignment = 31,
  sym_group = 32,
  sym_list = 33,
  sym__block_value = 34,
  sym_extension = 35,
  sym__list = 36,
  sym__group = 37,
  aux_sym_internal_reference_repeat1 = 38,
  aux_sym_string_repeat1 = 39,
  aux_sym_group_repeat1 = 40,
  aux_sym__list_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [aux_sym_path_reference_token1] = "path_reference_token1",
  [anon_sym_GT] = ">",
  [anon_sym_AMP] = "&",
  [aux_sym_bare_word_token1] = "bare_word_token1",
  [anon_sym_DQUOTE_DQUOTE] = "\"\"",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE2] = "\"",
  [anon_sym_AT_DQUOTE] = "@\"",
  [aux_sym_verbatim_token1] = "verbatim_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [aux_sym_extension_token1] = "extension_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_internal_reference] = "internal_reference",
  [sym_path_reference] = "path_reference",
  [sym_reference] = "reference",
  [sym_value] = "value",
  [sym_bare_word] = "bare_word",
  [sym_string] = "string",
  [sym_verbatim] = "verbatim",
  [sym_assignment] = "assignment",
  [sym__assignment] = "_assignment",
  [sym_group] = "group",
  [sym_list] = "list",
  [sym__block_value] = "_block_value",
  [sym_extension] = "extension",
  [sym__list] = "_list",
  [sym__group] = "_group",
  [aux_sym_internal_reference_repeat1] = "internal_reference_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym__list_repeat1] = "_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_path_reference_token1] = aux_sym_path_reference_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [aux_sym_bare_word_token1] = aux_sym_bare_word_token1,
  [anon_sym_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [anon_sym_AT_DQUOTE] = anon_sym_AT_DQUOTE,
  [aux_sym_verbatim_token1] = aux_sym_verbatim_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_extension_token1] = aux_sym_extension_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_internal_reference] = sym_internal_reference,
  [sym_path_reference] = sym_path_reference,
  [sym_reference] = sym_reference,
  [sym_value] = sym_value,
  [sym_bare_word] = sym_bare_word,
  [sym_string] = sym_string,
  [sym_verbatim] = sym_verbatim,
  [sym_assignment] = sym_assignment,
  [sym__assignment] = sym__assignment,
  [sym_group] = sym_group,
  [sym_list] = sym_list,
  [sym__block_value] = sym__block_value,
  [sym_extension] = sym_extension,
  [sym__list] = sym__list,
  [sym__group] = sym__group,
  [aux_sym_internal_reference_repeat1] = aux_sym_internal_reference_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym__list_repeat1] = aux_sym__list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_bare_word_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_verbatim_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_extension_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_internal_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_path_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_word] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__block_value] = {
    .visible = false,
    .named = true,
  },
  [sym_extension] = {
    .visible = true,
    .named = true,
  },
  [sym__list] = {
    .visible = false,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_internal_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = sym_list,
  },
  [3] = {
    [0] = sym_group,
  },
  [4] = {
    [0] = sym_list,
    [1] = sym_list,
  },
  [5] = {
    [0] = sym_group,
    [1] = sym_group,
  },
  [6] = {
    [0] = sym_list,
    [1] = sym_list,
    [2] = sym_list,
  },
  [7] = {
    [0] = sym_group,
    [1] = sym_group,
    [2] = sym_group,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__list, 2,
    sym__list,
    sym_list,
  sym__group, 2,
    sym__group,
    sym_group,
  aux_sym_group_repeat1, 3,
    aux_sym_group_repeat1,
    sym_group,
    sym_list,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 12,
  [48] = 48,
  [49] = 14,
  [50] = 15,
  [51] = 51,
  [52] = 16,
  [53] = 13,
  [54] = 54,
  [55] = 17,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 62,
  [65] = 57,
  [66] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 46,
        '&', 27,
        '.', 10,
        '/', 19,
        ':', 55,
        '<', 20,
        '=', 54,
        '>', 26,
        '@', 3,
        '[', 58,
        ']', 60,
        '{', 61,
        '}', 63,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(9);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(47);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 40,
        '&', 28,
        '/', 35,
        '@', 33,
        '[', 58,
        '\\', 34,
        '{', 61,
        0x0b, 31,
        '\f', 31,
        '\t', 32,
        '\n', 32,
        '\r', 32,
        ' ', 32,
      );
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(9);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 40,
        '&', 27,
        '.', 10,
        '/', 19,
        ':', 55,
        '<', 20,
        '=', 54,
        '>', 26,
        '@', 3,
        '[', 58,
        ']', 60,
        '{', 61,
        '}', 63,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '"') ADVANCE(16);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(53);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '"' ||
          lookahead == '[' ||
          lookahead == '{') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      ADVANCE_MAP(
        '\n', 32,
        '"', 41,
        '&', 28,
        '/', 35,
        '@', 33,
        '[', 59,
        '\\', 34,
        '{', 62,
        0x0b, 31,
        '\f', 31,
        '\t', 32,
        '\r', 32,
        ' ', 32,
      );
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '"') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      ADVANCE_MAP(
        '"', 41,
        '&', 28,
        '/', 35,
        '@', 33,
        '[', 59,
        '{', 62,
        '\t', 34,
        '\r', 34,
        ' ', 34,
        '\\', 34,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      if (lookahead == '"') ADVANCE(37);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_AT_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_AT_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '*') ADVANCE(50);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_extension_token1);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_extension_token1);
      if (lookahead == ',' ||
          lookahead == ';') ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 57},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 57},
  [50] = {.lex_state = 57},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 57},
  [53] = {.lex_state = 57},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 57},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 57},
  [61] = {.lex_state = 52},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [anon_sym_AT_DQUOTE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym_assignment] = STATE(59),
    [sym__assignment] = STATE(59),
    [sym_group] = STATE(59),
    [sym_list] = STATE(59),
    [sym_identifier] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(11), 1,
      aux_sym_bare_word_token1,
    ACTIONS(13), 1,
      anon_sym_DQUOTE_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_AT_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym__list,
    STATE(20), 1,
      sym_value,
    STATE(36), 1,
      sym__group,
    STATE(35), 4,
      sym_reference,
      sym_bare_word,
      sym_string,
      sym_verbatim,
  [40] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(26), 1,
      anon_sym_COLON,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(34), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym__group,
    STATE(39), 1,
      sym__list,
    ACTIONS(32), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    STATE(3), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [74] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_COLON,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym__group,
    STATE(39), 1,
      sym__list,
    STATE(3), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [107] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_COLON,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(45), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      sym__group,
    STATE(39), 1,
      sym__list,
    STATE(7), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [140] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_COLON,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym__group,
    STATE(39), 1,
      sym__list,
    STATE(4), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [173] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_COLON,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      sym__group,
    STATE(39), 1,
      sym__list,
    STATE(3), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [206] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_LT,
    STATE(18), 1,
      aux_sym_group_repeat1,
    STATE(26), 1,
      sym__list,
    STATE(27), 1,
      sym__group,
    STATE(44), 1,
      sym_extension,
    STATE(60), 2,
      sym_internal_reference,
      sym_path_reference,
  [238] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_LT,
    STATE(8), 1,
      aux_sym_group_repeat1,
    STATE(19), 1,
      sym__list,
    STATE(36), 1,
      sym__group,
    STATE(44), 1,
      sym_extension,
    STATE(60), 2,
      sym_internal_reference,
      sym_path_reference,
  [270] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_LT,
    STATE(18), 1,
      aux_sym_group_repeat1,
    STATE(42), 1,
      sym__group,
    STATE(43), 1,
      sym__list,
    STATE(44), 1,
      sym_extension,
    STATE(60), 2,
      sym_internal_reference,
      sym_path_reference,
  [302] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      sym_identifier,
    ACTIONS(53), 1,
      anon_sym_LT,
    STATE(10), 1,
      aux_sym_group_repeat1,
    STATE(38), 1,
      sym__list,
    STATE(41), 1,
      sym__group,
    STATE(44), 1,
      sym_extension,
    STATE(60), 2,
      sym_internal_reference,
      sym_path_reference,
  [334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    STATE(13), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(55), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [353] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [391] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    STATE(16), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [410] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [429] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_SLASH,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [445] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_LT,
    STATE(18), 1,
      aux_sym_group_repeat1,
    STATE(44), 1,
      sym_extension,
    ACTIONS(78), 2,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
    STATE(60), 2,
      sym_internal_reference,
      sym_path_reference,
  [469] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [534] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [560] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [573] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [638] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [715] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [739] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      anon_sym_EQ,
    ACTIONS(124), 1,
      anon_sym_COLON,
    STATE(23), 1,
      sym__list,
    STATE(28), 1,
      sym__group,
  [761] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [773] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [785] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [797] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 4,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 4,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [817] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(138), 1,
      anon_sym_LT,
    STATE(24), 2,
      sym_internal_reference,
      sym_path_reference,
  [831] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(55), 1,
      aux_sym_extension_token1,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(53), 1,
      aux_sym_internal_reference_repeat1,
  [844] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(142), 1,
      aux_sym_string_token1,
    ACTIONS(145), 1,
      anon_sym_DQUOTE2,
    STATE(48), 1,
      aux_sym_string_repeat1,
  [857] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(61), 1,
      aux_sym_extension_token1,
    ACTIONS(147), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      aux_sym_internal_reference_repeat1,
  [870] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(66), 1,
      aux_sym_extension_token1,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(52), 1,
      aux_sym_internal_reference_repeat1,
  [883] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(150), 1,
      aux_sym_string_token1,
    ACTIONS(152), 1,
      anon_sym_DQUOTE2,
    STATE(48), 1,
      aux_sym_string_repeat1,
  [896] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(68), 1,
      aux_sym_extension_token1,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      aux_sym_internal_reference_repeat1,
  [909] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(59), 1,
      aux_sym_extension_token1,
    ACTIONS(140), 1,
      anon_sym_SLASH,
    STATE(49), 1,
      aux_sym_internal_reference_repeat1,
  [922] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(154), 1,
      aux_sym_string_token1,
    ACTIONS(156), 1,
      anon_sym_DQUOTE2,
    STATE(51), 1,
      aux_sym_string_repeat1,
  [935] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(61), 1,
      aux_sym_extension_token1,
    ACTIONS(70), 1,
      anon_sym_SLASH,
  [945] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(158), 1,
      aux_sym_path_reference_token1,
  [952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_GT,
  [959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [966] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [973] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(166), 1,
      aux_sym_extension_token1,
  [980] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(168), 1,
      aux_sym_verbatim_token1,
  [987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_identifier,
  [994] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
  [1001] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
  [1008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_GT,
  [1015] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(178), 1,
      aux_sym_path_reference_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 74,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 206,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 270,
  [SMALL_STATE(11)] = 302,
  [SMALL_STATE(12)] = 334,
  [SMALL_STATE(13)] = 353,
  [SMALL_STATE(14)] = 372,
  [SMALL_STATE(15)] = 391,
  [SMALL_STATE(16)] = 410,
  [SMALL_STATE(17)] = 429,
  [SMALL_STATE(18)] = 445,
  [SMALL_STATE(19)] = 469,
  [SMALL_STATE(20)] = 482,
  [SMALL_STATE(21)] = 495,
  [SMALL_STATE(22)] = 508,
  [SMALL_STATE(23)] = 521,
  [SMALL_STATE(24)] = 534,
  [SMALL_STATE(25)] = 547,
  [SMALL_STATE(26)] = 560,
  [SMALL_STATE(27)] = 573,
  [SMALL_STATE(28)] = 586,
  [SMALL_STATE(29)] = 599,
  [SMALL_STATE(30)] = 612,
  [SMALL_STATE(31)] = 625,
  [SMALL_STATE(32)] = 638,
  [SMALL_STATE(33)] = 651,
  [SMALL_STATE(34)] = 664,
  [SMALL_STATE(35)] = 677,
  [SMALL_STATE(36)] = 690,
  [SMALL_STATE(37)] = 703,
  [SMALL_STATE(38)] = 715,
  [SMALL_STATE(39)] = 727,
  [SMALL_STATE(40)] = 739,
  [SMALL_STATE(41)] = 761,
  [SMALL_STATE(42)] = 773,
  [SMALL_STATE(43)] = 785,
  [SMALL_STATE(44)] = 797,
  [SMALL_STATE(45)] = 807,
  [SMALL_STATE(46)] = 817,
  [SMALL_STATE(47)] = 831,
  [SMALL_STATE(48)] = 844,
  [SMALL_STATE(49)] = 857,
  [SMALL_STATE(50)] = 870,
  [SMALL_STATE(51)] = 883,
  [SMALL_STATE(52)] = 896,
  [SMALL_STATE(53)] = 909,
  [SMALL_STATE(54)] = 922,
  [SMALL_STATE(55)] = 935,
  [SMALL_STATE(56)] = 945,
  [SMALL_STATE(57)] = 952,
  [SMALL_STATE(58)] = 959,
  [SMALL_STATE(59)] = 966,
  [SMALL_STATE(60)] = 973,
  [SMALL_STATE(61)] = 980,
  [SMALL_STATE(62)] = 987,
  [SMALL_STATE(63)] = 994,
  [SMALL_STATE(64)] = 1001,
  [SMALL_STATE(65)] = 1008,
  [SMALL_STATE(66)] = 1015,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_internal_reference, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_internal_reference, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_reference, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_reference, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_word, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 1, 0, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 2, 0, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 1, 0, 2),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 2, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 3, 0, 7),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 3, 0, 6),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_objecttext(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "objecttext",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
