/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_SLASH = 3,
  anon_sym_LT = 4,
  aux_sym_path_reference_token1 = 5,
  anon_sym_GT = 6,
  anon_sym_AMP = 7,
  sym_bare_word = 8,
  anon_sym_DQUOTE_DQUOTE = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_string_token1 = 11,
  anon_sym_DQUOTE2 = 12,
  anon_sym_AT_DQUOTE = 13,
  aux_sym_verbatim_token1 = 14,
  anon_sym_EQ = 15,
  anon_sym_COLON = 16,
  aux_sym_extension_token1 = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_DASH = 22,
  anon_sym_STAR = 23,
  anon_sym_PLUS = 24,
  anon_sym_LPAREN = 25,
  anon_sym_RPAREN = 26,
  sym_number = 27,
  sym_source_file = 28,
  sym_internal_reference = 29,
  sym_path_reference = 30,
  sym_reference = 31,
  sym_value = 32,
  sym_string = 33,
  sym_verbatim = 34,
  sym_assignment = 35,
  sym__assignment = 36,
  sym_group = 37,
  sym_list = 38,
  sym__block_value = 39,
  sym_extension = 40,
  sym__list = 41,
  sym__group = 42,
  sym_expression = 43,
  sym_urinary_expression = 44,
  sym_binary_expression = 45,
  sym_parenthesized_expression = 46,
  aux_sym_internal_reference_repeat1 = 47,
  aux_sym_string_repeat1 = 48,
  aux_sym_group_repeat1 = 49,
  aux_sym__list_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [aux_sym_path_reference_token1] = "path_reference_token1",
  [anon_sym_GT] = ">",
  [anon_sym_AMP] = "&",
  [sym_bare_word] = "bare_word",
  [anon_sym_DQUOTE_DQUOTE] = "\"\"",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE2] = "\"",
  [anon_sym_AT_DQUOTE] = "@\"",
  [aux_sym_verbatim_token1] = "verbatim_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [aux_sym_extension_token1] = "extension_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_internal_reference] = "internal_reference",
  [sym_path_reference] = "path_reference",
  [sym_reference] = "reference",
  [sym_value] = "value",
  [sym_string] = "string",
  [sym_verbatim] = "verbatim",
  [sym_assignment] = "assignment",
  [sym__assignment] = "_assignment",
  [sym_group] = "group",
  [sym_list] = "list",
  [sym__block_value] = "_block_value",
  [sym_extension] = "extension",
  [sym__list] = "_list",
  [sym__group] = "_group",
  [sym_expression] = "expression",
  [sym_urinary_expression] = "urinary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [aux_sym_internal_reference_repeat1] = "internal_reference_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym__list_repeat1] = "_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_path_reference_token1] = aux_sym_path_reference_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_bare_word] = sym_bare_word,
  [anon_sym_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [anon_sym_AT_DQUOTE] = anon_sym_AT_DQUOTE,
  [aux_sym_verbatim_token1] = aux_sym_verbatim_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_extension_token1] = aux_sym_extension_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_internal_reference] = sym_internal_reference,
  [sym_path_reference] = sym_path_reference,
  [sym_reference] = sym_reference,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [sym_verbatim] = sym_verbatim,
  [sym_assignment] = sym_assignment,
  [sym__assignment] = sym__assignment,
  [sym_group] = sym_group,
  [sym_list] = sym_list,
  [sym__block_value] = sym__block_value,
  [sym_extension] = sym_extension,
  [sym__list] = sym__list,
  [sym__group] = sym__group,
  [sym_expression] = sym_expression,
  [sym_urinary_expression] = sym_urinary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [aux_sym_internal_reference_repeat1] = aux_sym_internal_reference_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym__list_repeat1] = aux_sym__list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_bare_word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_verbatim_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_extension_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_internal_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_path_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__block_value] = {
    .visible = false,
    .named = true,
  },
  [sym_extension] = {
    .visible = true,
    .named = true,
  },
  [sym__list] = {
    .visible = false,
    .named = true,
  },
  [sym__group] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_urinary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_internal_reference_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = sym_list,
  },
  [3] = {
    [0] = sym_group,
  },
  [4] = {
    [0] = sym_list,
    [1] = sym_list,
  },
  [5] = {
    [0] = sym_group,
    [1] = sym_group,
  },
  [6] = {
    [0] = sym_list,
    [1] = sym_list,
    [2] = sym_list,
  },
  [7] = {
    [0] = sym_group,
    [1] = sym_group,
    [2] = sym_group,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__list, 2,
    sym__list,
    sym_list,
  sym__group, 2,
    sym__group,
    sym_group,
  aux_sym_group_repeat1, 3,
    aux_sym_group_repeat1,
    sym_group,
    sym_list,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 12,
  [56] = 56,
  [57] = 9,
  [58] = 10,
  [59] = 11,
  [60] = 60,
  [61] = 61,
  [62] = 8,
  [63] = 16,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 71,
  [73] = 64,
  [74] = 66,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 5},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_binary_expression,
    sym_number,
    sym_parenthesized_expression,
    sym_reference,
    sym_urinary_expression,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 51,
        '&', 34,
        '(', 71,
        ')', 72,
        '*', 69,
        '+', 70,
        '-', 67,
        '.', 11,
        '/', 26,
        ':', 59,
        '<', 27,
        '=', 58,
        '>', 33,
        '@', 3,
        '[', 62,
        ']', 63,
        '{', 64,
        '}', 65,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(52);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 46,
        '&', 34,
        '(', 71,
        '-', 67,
        '.', 12,
        '/', 7,
        '@', 3,
        '[', 62,
        '{', 64,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '"', 46,
        '&', 34,
        '(', 71,
        '-', 68,
        '.', 42,
        '/', 41,
        '@', 40,
        '[', 62,
        '\\', 39,
        '{', 64,
        0x0b, 37,
        '\f', 37,
        '\t', 38,
        '\n', 38,
        '\r', 38,
        ' ', 38,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 6:
      if (lookahead == '&') ADVANCE(34);
      if (lookahead == '(') ADVANCE(71);
      if (lookahead == '-') ADVANCE(67);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(10);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 14:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 46,
        '&', 34,
        '(', 71,
        ')', 72,
        '*', 69,
        '+', 70,
        '-', 67,
        '.', 11,
        '/', 26,
        ':', 59,
        '<', 27,
        '=', 58,
        '>', 33,
        '@', 3,
        '[', 62,
        ']', 63,
        '{', 64,
        '}', 65,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 45,
        ')', 72,
        '*', 69,
        '+', 70,
        '-', 66,
        '.', 13,
        '/', 26,
        ':', 59,
        '<', 27,
        '[', 62,
        ']', 63,
        '{', 64,
        '}', 65,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '%') ADVANCE(77);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == 'd') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '%') ADVANCE(77);
      if (lookahead == 'd') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_path_reference_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '*') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '\n') ADVANCE(37);
      if (lookahead == '"' ||
          lookahead == '[' ||
          lookahead == '{') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_bare_word);
      ADVANCE_MAP(
        '\n', 38,
        '"', 46,
        '&', 34,
        '(', 71,
        '-', 68,
        '.', 42,
        '/', 41,
        '@', 40,
        '[', 62,
        '\\', 39,
        '{', 64,
        0x0b, 37,
        '\f', 37,
        '\t', 38,
        '\r', 38,
        ' ', 38,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '"') ADVANCE(46);
      if (lookahead == '&') ADVANCE(34);
      if (lookahead == '(') ADVANCE(71);
      if (lookahead == '-') ADVANCE(68);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '@') ADVANCE(40);
      if (lookahead == '[') ADVANCE(62);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '"') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_bare_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(44);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      if (lookahead == '"') ADVANCE(44);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AT_DQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '*') ADVANCE(53);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == '\\') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_verbatim_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_extension_token1);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_extension_token1);
      if (lookahead == ',' ||
          lookahead == ';') ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '.') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(77);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'd') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(77);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == 'd') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '%') ADVANCE(77);
      if (lookahead == 'd') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'd') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 15},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 15},
  [38] = {.lex_state = 15},
  [39] = {.lex_state = 15},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 15},
  [42] = {.lex_state = 15},
  [43] = {.lex_state = 15},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 15},
  [47] = {.lex_state = 15},
  [48] = {.lex_state = 15},
  [49] = {.lex_state = 15},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 15},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 61},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 61},
  [58] = {.lex_state = 61},
  [59] = {.lex_state = 61},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 61},
  [63] = {.lex_state = 61},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 15},
  [68] = {.lex_state = 56},
  [69] = {.lex_state = 61},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 15},
  [72] = {.lex_state = 15},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [anon_sym_AT_DQUOTE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(65),
    [sym_assignment] = STATE(70),
    [sym__assignment] = STATE(70),
    [sym_group] = STATE(70),
    [sym_list] = STATE(70),
    [sym_identifier] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(11), 1,
      sym_bare_word,
    ACTIONS(13), 1,
      anon_sym_DQUOTE_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_AT_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_number,
    STATE(19), 1,
      sym_expression,
    STATE(29), 1,
      sym__list,
    STATE(30), 1,
      sym__group,
    STATE(42), 1,
      sym_value,
    STATE(31), 2,
      sym_string,
      sym_verbatim,
    STATE(13), 4,
      sym_reference,
      sym_urinary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
  [56] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_COLON,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym__list,
    STATE(49), 1,
      sym__group,
    ACTIONS(38), 2,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    STATE(3), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [90] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym__list,
    STATE(49), 1,
      sym__group,
    STATE(6), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [123] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym__list,
    STATE(49), 1,
      sym__group,
    STATE(7), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [156] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      sym__list,
    STATE(49), 1,
      sym__group,
    STATE(3), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [189] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym__list,
    STATE(49), 1,
      sym__group,
    STATE(3), 6,
      sym_assignment,
      sym__assignment,
      sym_group,
      sym_list,
      sym__block_value,
      aux_sym__list_repeat1,
  [222] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(57), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [245] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_SLASH,
    STATE(8), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(61), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [268] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(63), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [291] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_SLASH,
    STATE(12), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(68), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_SLASH,
    STATE(10), 1,
      aux_sym_internal_reference_repeat1,
    ACTIONS(70), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_SLASH,
    ACTIONS(72), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [357] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_SLASH,
    ACTIONS(76), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [377] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_SLASH,
    ACTIONS(80), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [397] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(63), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [417] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(86), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [437] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_SLASH,
    ACTIONS(90), 11,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_RPAREN,
  [457] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(98), 3,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [478] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_LT,
    STATE(27), 1,
      aux_sym_group_repeat1,
    STATE(32), 1,
      sym__group,
    STATE(34), 1,
      sym__list,
    STATE(52), 1,
      sym_extension,
    STATE(69), 2,
      sym_internal_reference,
      sym_path_reference,
  [510] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_LT,
    STATE(23), 1,
      aux_sym_group_repeat1,
    STATE(44), 1,
      sym__group,
    STATE(45), 1,
      sym__list,
    STATE(52), 1,
      sym_extension,
    STATE(69), 2,
      sym_internal_reference,
      sym_path_reference,
  [542] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_LT,
    STATE(20), 1,
      aux_sym_group_repeat1,
    STATE(29), 1,
      sym__list,
    STATE(30), 1,
      sym__group,
    STATE(52), 1,
      sym_extension,
    STATE(69), 2,
      sym_internal_reference,
      sym_path_reference,
  [574] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_LT,
    STATE(27), 1,
      aux_sym_group_repeat1,
    STATE(46), 1,
      sym__group,
    STATE(47), 1,
      sym__list,
    STATE(52), 1,
      sym_extension,
    STATE(69), 2,
      sym_internal_reference,
      sym_path_reference,
  [606] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      sym_number,
    STATE(51), 1,
      sym_expression,
    STATE(13), 4,
      sym_reference,
      sym_urinary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
  [631] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      sym_number,
    STATE(15), 1,
      sym_expression,
    STATE(13), 4,
      sym_reference,
      sym_urinary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
  [656] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(104), 1,
      anon_sym_AMP,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      sym_number,
    STATE(17), 1,
      sym_expression,
    STATE(13), 4,
      sym_reference,
      sym_urinary_expression,
      sym_binary_expression,
      sym_parenthesized_expression,
  [681] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(113), 1,
      anon_sym_LT,
    STATE(27), 1,
      aux_sym_group_repeat1,
    STATE(52), 1,
      sym_extension,
    ACTIONS(116), 2,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
    STATE(69), 2,
      sym_internal_reference,
      sym_path_reference,
  [705] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [757] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [770] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [783] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [835] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [848] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [925] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [961] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 6,
      sym_identifier,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [985] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 1,
      anon_sym_EQ,
    ACTIONS(162), 1,
      anon_sym_COLON,
    STATE(39), 1,
      sym__list,
    STATE(41), 1,
      sym__group,
  [1007] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_SLASH,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(98), 3,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PLUS,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 4,
      sym_identifier,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1042] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(172), 1,
      anon_sym_LT,
    STATE(14), 2,
      sym_internal_reference,
      sym_path_reference,
  [1056] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(70), 1,
      aux_sym_extension_token1,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    STATE(58), 1,
      aux_sym_internal_reference_repeat1,
  [1069] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(176), 1,
      aux_sym_string_token1,
    ACTIONS(179), 1,
      anon_sym_DQUOTE2,
    STATE(56), 1,
      aux_sym_string_repeat1,
  [1082] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(61), 1,
      aux_sym_extension_token1,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    STATE(62), 1,
      aux_sym_internal_reference_repeat1,
  [1095] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(63), 1,
      aux_sym_extension_token1,
    ACTIONS(181), 1,
      anon_sym_SLASH,
    STATE(58), 1,
      aux_sym_internal_reference_repeat1,
  [1108] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(68), 1,
      aux_sym_extension_token1,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    STATE(55), 1,
      aux_sym_internal_reference_repeat1,
  [1121] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(184), 1,
      aux_sym_string_token1,
    ACTIONS(186), 1,
      anon_sym_DQUOTE2,
    STATE(56), 1,
      aux_sym_string_repeat1,
  [1134] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(188), 1,
      aux_sym_string_token1,
    ACTIONS(190), 1,
      anon_sym_DQUOTE2,
    STATE(60), 1,
      aux_sym_string_repeat1,
  [1147] = 4,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(57), 1,
      aux_sym_extension_token1,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    STATE(58), 1,
      aux_sym_internal_reference_repeat1,
  [1160] = 3,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(63), 1,
      aux_sym_extension_token1,
    ACTIONS(84), 1,
      anon_sym_SLASH,
  [1170] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_GT,
  [1177] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
  [1184] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(196), 1,
      aux_sym_path_reference_token1,
  [1191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
  [1198] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(200), 1,
      aux_sym_verbatim_token1,
  [1205] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(202), 1,
      aux_sym_extension_token1,
  [1212] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [1219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
  [1226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_identifier,
  [1233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_GT,
  [1240] = 2,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(212), 1,
      aux_sym_path_reference_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 156,
  [SMALL_STATE(7)] = 189,
  [SMALL_STATE(8)] = 222,
  [SMALL_STATE(9)] = 245,
  [SMALL_STATE(10)] = 268,
  [SMALL_STATE(11)] = 291,
  [SMALL_STATE(12)] = 314,
  [SMALL_STATE(13)] = 337,
  [SMALL_STATE(14)] = 357,
  [SMALL_STATE(15)] = 377,
  [SMALL_STATE(16)] = 397,
  [SMALL_STATE(17)] = 417,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 457,
  [SMALL_STATE(20)] = 478,
  [SMALL_STATE(21)] = 510,
  [SMALL_STATE(22)] = 542,
  [SMALL_STATE(23)] = 574,
  [SMALL_STATE(24)] = 606,
  [SMALL_STATE(25)] = 631,
  [SMALL_STATE(26)] = 656,
  [SMALL_STATE(27)] = 681,
  [SMALL_STATE(28)] = 705,
  [SMALL_STATE(29)] = 718,
  [SMALL_STATE(30)] = 731,
  [SMALL_STATE(31)] = 744,
  [SMALL_STATE(32)] = 757,
  [SMALL_STATE(33)] = 770,
  [SMALL_STATE(34)] = 783,
  [SMALL_STATE(35)] = 796,
  [SMALL_STATE(36)] = 809,
  [SMALL_STATE(37)] = 822,
  [SMALL_STATE(38)] = 835,
  [SMALL_STATE(39)] = 848,
  [SMALL_STATE(40)] = 861,
  [SMALL_STATE(41)] = 874,
  [SMALL_STATE(42)] = 887,
  [SMALL_STATE(43)] = 900,
  [SMALL_STATE(44)] = 913,
  [SMALL_STATE(45)] = 925,
  [SMALL_STATE(46)] = 937,
  [SMALL_STATE(47)] = 949,
  [SMALL_STATE(48)] = 961,
  [SMALL_STATE(49)] = 973,
  [SMALL_STATE(50)] = 985,
  [SMALL_STATE(51)] = 1007,
  [SMALL_STATE(52)] = 1022,
  [SMALL_STATE(53)] = 1032,
  [SMALL_STATE(54)] = 1042,
  [SMALL_STATE(55)] = 1056,
  [SMALL_STATE(56)] = 1069,
  [SMALL_STATE(57)] = 1082,
  [SMALL_STATE(58)] = 1095,
  [SMALL_STATE(59)] = 1108,
  [SMALL_STATE(60)] = 1121,
  [SMALL_STATE(61)] = 1134,
  [SMALL_STATE(62)] = 1147,
  [SMALL_STATE(63)] = 1160,
  [SMALL_STATE(64)] = 1170,
  [SMALL_STATE(65)] = 1177,
  [SMALL_STATE(66)] = 1184,
  [SMALL_STATE(67)] = 1191,
  [SMALL_STATE(68)] = 1198,
  [SMALL_STATE(69)] = 1205,
  [SMALL_STATE(70)] = 1212,
  [SMALL_STATE(71)] = 1219,
  [SMALL_STATE(72)] = 1226,
  [SMALL_STATE(73)] = 1233,
  [SMALL_STATE(74)] = 1240,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_internal_reference, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_internal_reference, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_reference, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_reference, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_urinary_expression, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_urinary_expression, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__list, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__group, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 2, 0, 5),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 2, 0, 4),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 3, 0, 7),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 3, 0, 6),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 1, 0, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_value, 1, 0, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_internal_reference_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_objecttext(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "objecttext",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
